spring.application.name=agent.engine

# PostgreSQL (Railway - usando variáveis de ambiente)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HTTP Compression
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,text/plain,text/html
