spring.application.name=agent.engine

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-wandering-feather-ajji1jdn-pooler.c-3.us-east-2.aws.neon.tech/agent_skill?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_A0qbCOFJet5u
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# HTTP Compression
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,text/plain,text/html
